Name=bash
Version=5.2.37
Namespace=app
Description="GNU Bash"
Url=https://mirrors.kernel.org/gnu/bash/bash-5.2.37.tar.gz
Dependencies=(glibc ncurses)
Build() {
cd "$SourceDirectory"
./configure --prefix=/usr --without-bash-malloc --disable-nls
make -j"$(nproc)"
make DESTDIR="$InstallRoot" install
}
