Name=bc
Version=1.07.1
Namespace=GNU
Description="GNU bc calculator"
Url=https://mirrors.kernel.org/gnu/bc/bc-1.07.1.tar.gz
ConfigureFlags=(--disable-nls --with-readline)
Dependencies=(glibc readline)
