Name=binutils
Version=2.44
Namespace=GNU
Description="GNU Binutils"
Url=https://mirrors.kernel.org/gnu/binutils/binutils-2.44.tar.xz
ConfigureFlags=(--disable-nls --disable-werror --enable-shared --disable-gdb --disable-gprofng)
Dependencies=(glibc)
ExtraPackages=(texinfo)
