Name=ca-certificates
Version=2025-02-25
Namespace=app
Description="Mozilla CA certificate bundle"
Url=https://curl.se/ca/cacert-2025-02-25.pem
ArchiveFormat=plain
Dependencies=()
Build() {
mkdir -p "$InstallRoot/etc/ssl/certs/okra"
cp "$Archive" "$InstallRoot/etc/ssl/certs/ca-certificates.crt"
cp "$Archive" "$InstallRoot/etc/ssl/certs/okra/ca-bundle.crt"
}
