Name=curl
Version=8.12.1
Namespace=app
Description="curl data transfer tool"
Url=https://curl.se/download/curl-8.12.1.tar.xz
ConfigureFlags=(--disable-static --without-ssl --without-libpsl --without-zstd --without-brotli --without-libssh2 --disable-ldap --disable-manual --without-ca-bundle --without-ca-path)
Dependencies=(glibc)
