Name=dialog
Version=1.3-20260107
Namespace=app
Description="dialog TUI widget tool"
Url=https://invisible-mirror.net/archives/dialog/dialog-1.3-20260107.tgz
Dependencies=(glibc ncurses)
Build() {
cd "$SourceDirectory"
./configure --prefix=/usr --disable-nls --with-ncurses --disable-rpath
make -j"$(nproc)"
make DESTDIR="$InstallRoot" install
}
