Name=e2fsprogs
Version=1.47.2
Namespace=app
Description="ext2 ext3 ext4 file system utilities"
Url=https://mirrors.edge.kernel.org/pub/linux/kernel/people/tytso/e2fsprogs/v1.47.2/e2fsprogs-1.47.2.tar.xz
BuildSystem=autoconf
ConfigureFlags=(--disable-nls --disable-elf-shlibs --disable-uuidd --disable-fsck --without-crond-dir)
Dependencies=(glibc)
