Name=ed
Version=1.22
Namespace=GNU
Description="GNU ed line editor"
Url=https://mirrors.kernel.org/gnu/ed/ed-1.22.tar.lz
ArchiveFormat=lz
Dependencies=(glibc)
Build() {
cd "$SourceDirectory"
./configure --prefix=/usr
make -j"$(nproc)"
make DESTDIR="$InstallRoot" install
}
