Name=expat
Version=2.6.4
Namespace=app
Description="expat XML parser library"
Url=https://github.com/libexpat/libexpat/releases/download/R_2_6_4/expat-2.6.4.tar.bz2
ConfigureFlags=(--disable-static --without-docbook --without-xmlwf)
Dependencies=(glibc)
