Name=flex
Version=2.6.4
Namespace=app
Description="flex lexical analyser"
Url=https://github.com/westes/flex/releases/download/v2.6.4/flex-2.6.4.tar.gz
ConfigureFlags=(--disable-nls --disable-shared --without-bison)
Dependencies=(glibc)
