Name=gdbm
Version=1.24
Namespace=GNU
Description="GNU dbm database library"
Url=https://mirrors.kernel.org/gnu/gdbm/gdbm-1.24.tar.gz
ConfigureFlags=(--disable-static --enable-libgdbm-compat)
Dependencies=(glibc)
