Name=gettext
Version=0.24
Namespace=GNU
Description="GNU gettext internationalization tools"
Url=https://mirrors.kernel.org/gnu/gettext/gettext-0.24.tar.xz
ConfigureFlags=(--disable-nls --disable-static --without-emacs --without-git --without-bzip2 --without-xz --without-libxml2 --without-libunistring --without-libintl-prefix --disable-java --disable-csharp)
Dependencies=(glibc)
