Name=glibc
Version=2.43
Namespace=app
Description="GNU C Library"
Url=https://mirrors.kernel.org/gnu/glibc/glibc-2.43.tar.xz
Dependencies=()
Build() {
mkdir -p "$WorkRoot/glibc-build"
cd "$WorkRoot/glibc-build"
echo 'rootscheme: unix' > configparms
"$SourceDirectory/configure" --prefix=/usr --enable-kernel=5.10 --disable-werror --without-gd --disable-nscd
make -j"$(nproc)"
make DESTDIR="$InstallRoot" install
}
ExtraPackages=(bison gawk texinfo)
