Name=gmp
Version=6.3.0
Namespace=GNU
Description="GNU MP bignum library"
Url=https://mirrors.kernel.org/gnu/gmp/gmp-6.3.0.tar.xz
ConfigureFlags=(--enable-shared --disable-static)
Dependencies=(glibc)
