Name=gsasl
Version=2.2.2
Namespace=app
Description="GNU SASL library"
Url=https://mirrors.kernel.org/gnu/gsasl/gsasl-2.2.2.tar.gz
ConfigureFlags=(--disable-nls --disable-static --without-stringprep)
Dependencies=(glibc)
