Name=iputils
Version=20240117
Namespace=app
Description="iputils network tools"
Url=https://github.com/iputils/iputils/releases/download/20240117/iputils-20240117.tar.xz
Dependencies=(glibc openssl)
Build() {
cd "$SourceDirectory"
meson setup build --prefix=/usr --buildtype=release -DBUILD_MANS=false -DNO_SETCAP_OR_SUID=true -DUSE_IDN=false -DUSE_GETTEXT=false -DUSE_CAP=false
meson compile -C build -j "$(nproc)"
DESTDIR="$InstallRoot" meson install -C build
}
ExtraPackages=(meson ninja-build)
