Name=kmod
Version=33
Namespace=app
Description="kernel module tools"
Url=https://mirrors.edge.kernel.org/pub/linux/utils/kernel/kmod/kmod-33.tar.xz
ConfigureFlags=(--disable-nls --with-zstd --without-openssl --disable-manpages --with-rootlibdir=/usr/lib)
Dependencies=(glibc zstd)
