Name=libcap
Version=2.73
Namespace=app
Description="POSIX capabilities library"
Url=https://mirrors.kernel.org/pub/linux/libs/security/linux-privs/libcap2/libcap-2.73.tar.xz
Dependencies=(glibc)
Build() {
cd "$SourceDirectory"
make -j"$(nproc)" RAISE_SETFCAP=no lib=lib
make DESTDIR="$InstallRoot" RAISE_SETFCAP=no lib=lib prefix=/usr install
}
