Name=libtirpc
Version=1.3.6
Namespace=app
Description="transport independent RPC library"
Url=https://downloads.sourceforge.net/project/libtirpc/libtirpc/1.3.6/libtirpc-1.3.6.tar.bz2
ConfigureFlags=(--disable-static --disable-gssapi)
Dependencies=(glibc)
