Name=libtasn1
Version=4.20.0
Namespace=app
Description="ASN.1 structure management library"
Url=https://mirrors.kernel.org/gnu/libtasn1/libtasn1-4.20.0.tar.gz
ConfigureFlags=(--disable-static --disable-doc)
Dependencies=(glibc)
