Name=ncurses
Version=6.5
Namespace=app
Description="ncurses terminal library"
Url=https://mirrors.kernel.org/gnu/ncurses/ncurses-6.5.tar.gz
Dependencies=(glibc)
Build() {
cd "$SourceDirectory"
./configure --prefix=/usr --with-shared --without-ada --without-tests --disable-nls --without-cxx-binding --with-shared-only --disable-stripping
make -j"$(nproc)"
make DESTDIR="$InstallRoot" install
cd "$InstallRoot/usr/lib"
WideLibrary="libncurses.so.6"
[ -e libncursesw.so.6 ] && WideLibrary="libncursesw.so.6"
ln -sf "$WideLibrary" libtinfo.so.6
ln -sf "$WideLibrary" libncurses.so.6
ln -sf "$WideLibrary" libcurses.so.6
}
