Name=nettle
Version=3.10.1
Namespace=app
Description="low level cryptographic library"
Url=https://mirrors.kernel.org/gnu/nettle/nettle-3.10.1.tar.gz
ConfigureFlags=(--disable-static --disable-documentation --enable-shared)
Dependencies=(glibc gmp)
