Name=openssl
Version=3.4.1
Namespace=app
Description="OpenSSL toolkit"
Url=https://github.com/openssl/openssl/releases/download/openssl-3.4.1/openssl-3.4.1.tar.gz
Dependencies=(glibc)
Build() {
cd "$SourceDirectory"
./Configure --prefix=/usr --openssldir=/etc/ssl --libdir=lib shared no-tests no-docs
make -j"$(nproc)"
make DESTDIR="$InstallRoot" install_sw install_ssldirs
}
