Name=pcre2
Version=10.44
Namespace=app
Description="Perl compatible regular expression library"
Url=https://github.com/PCRE2Project/pcre2/releases/download/pcre2-10.44/pcre2-10.44.tar.gz
ConfigureFlags=(--disable-static --enable-pcre2-16 --enable-pcre2-32 --enable-jit --disable-pcre2grep-libz --disable-pcre2grep-libbz2 --disable-pcre2test-libreadline)
Dependencies=(glibc)
