Name=perl
Version=5.40.0
Namespace=app
Description="Perl programming language"
Url=https://www.cpan.org/src/5.0/perl-5.40.0.tar.gz
Dependencies=(glibc)
Build() {
cd "$SourceDirectory"
./Configure -des -Dprefix=/usr -Dvendorprefix=/usr -Dman1dir=/usr/share/man/man1 -Dman3dir=/usr/share/man/man3 -Dsiteman1dir=/usr/share/man/man1 -Dsiteman3dir=/usr/share/man/man3 -Dman1ext=1 -Dman3ext=3pm -Dpager=/usr/bin/less -Ulocincpth= -Uloclibpth= -Duseshrplib -Dlibperl=libperl.so.5.40.0 -Dusethreads
make -j"$(nproc)"
make DESTDIR="$InstallRoot" install
find "$InstallRoot" -name '.packlist' -delete
find "$InstallRoot" -name 'perllocal.pod' -delete
}
