Name=pkgconf
Version=2.3.0
Namespace=app
Description="pkg-config implementation"
Url=https://distfiles.ariadne.space/pkgconf/pkgconf-2.3.0.tar.xz
ConfigureFlags=(--disable-static)
Dependencies=(glibc)
