Name=procps
Version=4.0.5
Namespace=app
Description="procps process utilities"
Url=https://gitlab.com/procps-ng/procps/-/archive/v4.0.5/procps-v4.0.5.tar.gz
Dependencies=(glibc ncurses)
Build() {
cd "$SourceDirectory"
./autogen.sh --no-po
./configure --prefix=/usr --disable-nls --disable-static --disable-kill --without-systemd --without-elogind
make -j"$(nproc)"
make DESTDIR="$InstallRoot" install
}
ExtraPackages=(autoconf automake libtool pkg-config gettext)
