Name=python
Version=3.13.1
Namespace=app
Description="Python programming language"
Url=https://www.python.org/ftp/python/3.13.1/Python-3.13.1.tar.xz
Dependencies=(glibc libffi expat sqlite zlib openssl readline ncurses)
Build() {
cd "$SourceDirectory"
./configure --prefix=/usr --enable-shared --with-system-expat --with-system-ffi --without-ensurepip --disable-test-modules --with-computed-gotos
make -j"$(nproc)"
make DESTDIR="$InstallRoot" install
}
