Name=rsync
Version=3.4.1
Namespace=app
Description="rsync file transfer tool"
Url=https://download.samba.org/pub/rsync/src/rsync-3.4.1.tar.gz
ConfigureFlags=(--disable-nls --disable-static --disable-xxhash --disable-zstd --disable-lz4 --disable-openssl --disable-md2man --with-included-popt --with-included-zlib)
Dependencies=(glibc)
