Name=shadow
Version=4.17.2
Namespace=app
Description="shadow password suite"
Url=https://github.com/shadow-maint/shadow/releases/download/4.17.2/shadow-4.17.2.tar.xz
ConfigureFlags=(--disable-nls --without-libbsd --without-selinux --without-audit --without-libcrack --disable-static --with-group-name-max-length=32)
Dependencies=(glibc)
