Name=sqlite
Version=3.47.0
Namespace=app
Description="SQLite database library"
Url=https://sqlite.org/2024/sqlite-autoconf-3470000.tar.gz
ConfigureFlags=(--disable-static --enable-threadsafe --enable-fts5 --enable-json1 --enable-rtree)
Dependencies=(glibc readline zlib)
