Name=strace
Version=6.13
Namespace=app
Description="system call tracer"
Url=https://github.com/strace/strace/releases/download/v6.13/strace-6.13.tar.xz
ConfigureFlags=(--disable-nls --disable-mpers --enable-mpers=no --without-libdw --without-libunwind)
Dependencies=(glibc)
