Name=sudo
Version=1.9.16
Namespace=app
Description="sudo privilege tool"
Url=https://www.sudo.ws/dist/sudo-1.9.16.tar.gz
ConfigureFlags=(--disable-nls --without-pam --with-env-editor --disable-static --disable-gcrypt --without-openssl --with-rundir=/run/sudo --with-vardir=/var/db/sudo)
Dependencies=(glibc)
Build() {
cd "$SourceDirectory"
./configure --prefix=/usr --disable-nls --without-pam --with-env-editor --disable-static --disable-gcrypt --without-openssl --with-rundir=/run/sudo --with-vardir=/var/db/sudo
make -j"$(nproc)"
fakeroot make DESTDIR="$InstallRoot" install
}
