Name=texinfo
Version=7.2
Namespace=GNU
Description="GNU Texinfo documentation system"
Url=https://mirrors.kernel.org/gnu/texinfo/texinfo-7.2.tar.xz
ConfigureFlags=(--disable-nls --disable-static)
Dependencies=(glibc ncurses)
