Name=util-linux
Version=2.40.4
Namespace=app
Description="util-linux base system utilities"
Url=https://mirrors.edge.kernel.org/pub/linux/utils/util-linux/v2.40/util-linux-2.40.4.tar.xz
ConfigureFlags=(--disable-nls --without-python --disable-bash-completion --disable-asciidoc --disable-use-tty-group --disable-makeinstall-chown --disable-liblastlog2 --without-udev --without-systemd)
Dependencies=(glibc)
