Name=wget
Version=1.25.0
Namespace=GNU
Description="GNU Wget"
Url=https://mirrors.kernel.org/gnu/wget/wget-1.25.0.tar.gz
ConfigureFlags=(--disable-nls --without-ssl --without-libpsl --without-zlib --without-libidn --without-pcre --without-libiconv-prefix --disable-rpath)
Dependencies=(glibc)
