Name=xz
Version=5.6.4
Namespace=app
Description="XZ Utils compression tools"
Url=https://github.com/tukaani-project/xz/releases/download/v5.6.4/xz-5.6.4.tar.gz
ConfigureFlags=(--disable-nls --disable-static)
Dependencies=(glibc)
