Name=zstd
Version=1.5.7
Namespace=app
Description="Zstandard compression tools"
Url=https://github.com/facebook/zstd/releases/download/v1.5.7/zstd-1.5.7.tar.gz
Dependencies=(glibc)
Build() {
cd "$SourceDirectory"
make -j"$(nproc)" -C lib libzstd
make -j"$(nproc)" -C programs
make -C lib install DESTDIR="$InstallRoot" PREFIX=/usr
make -C programs install DESTDIR="$InstallRoot" PREFIX=/usr
}
